In [1]:
import numpy as np
from copy import copy
import random
import time
import math
import sympy as sy
import itertools
from fractions import Fraction
import requests
from bs4 import BeautifulSoup
from IPython.display import Markdown, display

In [11]:
url='https://www.janestreet.com/puzzles/robot-archery-index/'
res = requests.get(url)
soup = BeautifulSoup(res.content, 'html.parser')
y =[text for text in soup.body.stripped_strings]
#display([[i,j] for i,j in enumerate(y)])
display(Markdown("### "+y[8]+"\n\n"+str("\n".join(y[10:76]))))

### December 2021 : Puzzle

After a grueling year filled with a wide variety of
robot
sporting
events
, we have arrived at the final event of the year:
Robot Archery
. Four robots have qualified for this year’s finals, and have been seeded in the following order:
Robot
Seed
Aaron
1
Barron
2
Caren
3
Darrin
4
The robots will take turns shooting arrows at a target
1
, starting with Aaron and proceeding in order by seed. When it is a given robot’s turn, they shoot a single arrow. If it is closer to the center of the target than
all
previous arrows by all players, that robot remains in the tournament, going to the back of the queue to await their next turn. Otherwise that robot is eliminated immediately. The last robot remaining in the queue is the winner.
For example, here is how
last year’s
finals went, in which
Caren
was the winner. (Oddly enough it involved the same robots in the same seeding.)
Turn
Robot
Distance
1
Aaron
10nm
2
Barron
8nm
3
Caren
7nm
4
Darrin
1km
5
Aaron
9nm
6
Barron
2nm
7
Caren
1nm
8
Barron
1Ym
2
To ten decimal places, what is the probability that
Darrin
will be this year’s winner?
(Or, if you want to send in the
exact answer
, that’s fine too!)
[1] Each robot is equally skilled. Which is to say: for any region
R
on the target with nonzero area, the robots all have the same positive probability of landing an arrow within
R
on any given shot.
[2] It’s a large target.

In [3]:
# build out the probability tree
def tree(p,stopper):
    game = [(np.ones(p),Fraction(1,1),1,1)]  # live players,probability, number of shots, next player
    result = []
    
    while len(game) >0:
        (players,prob,num,x) = game.pop()
        if np.sum(players) ==1:
            result.append([np.argmax(players)+1,prob])
        elif num >stopper:
            result.append([0,prob])
        else:
            num +=1
            pass_prob = prob * Fraction(1,num)
            fail_prob = prob * Fraction(num-1,num)
            fail_players = copy(players)
            fail_players[x] = 0
            nextp = (x +1) % p
            while players[nextp] ==0:
                nextp = (nextp +1) % p
            game.append([players,pass_prob,num,nextp])
            game.append([fail_players,fail_prob,num,nextp])
    print(len(result),"total paths")
    return [(n,float(np.sum([j for i,j in result if i==n])))for n in range(p+1)]


In [4]:
output = tree(4,18)
for i in range(5):
    print("Player {} has a {:.10f} probability".format(output[i][0],output[i][1]))

988 total paths
Player 0 has a 0.0000000000 probability
Player 1 has a 0.3711532348 probability
Player 2 has a 0.2421885526 probability
Player 3 has a 0.2032205617 probability
Player 4 has a 0.1834376509 probability


In [5]:
url='https://www.janestreet.com/puzzles/robot-archery-solution/'
res = requests.get(url)
soup = BeautifulSoup(res.content, 'html.parser')
y =[text for text in soup.body.stripped_strings]
#display([[i,j] for i,j in enumerate(y)])
display(Markdown("### "+y[7]+"\n\n"+str("\n".join(y[10:219]))))

### Robot Archery

[Above is a Mathematica-derived solution to the systems of equations
described in the 4-player tournament described below]
Without loss of generality we can assume an arrow’s distance to the center of the target is U[0,1] distributed. Let
P
j,k
(
x
) denote the probability that Player
j
out of
k
in the
current
line will eventually win the game, given that the current best dart is at distance
x
.
In a 2-player archery tournament, we would have
P
1,2
(
x
) +
P
2,2
(
x
) = 1,
P
1,2
(0) = 0, and
P
1,2
(
x
) = ∫
0
x
P
2,2
(
u
) d
u
. Taking derivatives of both sides in that last equation and substituing gives
P
‘
1,2
(
x
) = −
P
1,2
(x). Solving gives
P
1,2
(
x
) = 1−e
−
x
.
In the 3-player version of the game, we get the following system of equations:
P
1,3
(
x
) = ∫
0
x
P
3,3
(
u
) d
u
P
2,3
(
x
) = (1 -
x
)
P
1,2
(
x
) + ∫
0
x
P
1,3
(
u
) d
u
P
1,3
(
x
) +
P
2,3
(
x
) +
P
3,3
(
x
) = 1
P
1,3
(0) =
P
2,3
(0) = 0.
And for the 4-player version we have the following:
P
1,4
(
x
) = ∫
0
x
P
4,4
(
u
) d
u
P
2,4
(
x
) = (1 -
x
)
P
1,3
(
x
) + ∫
0
x
P
1,4
(
u
) d
u
P
3,4
(
x
) = (1 -
x
)
P
2,3
(
x
) + ∫
0
x
P
2,4
(
u
) d
u
P
1,4
(
x
) +
P
2,4
(
x
) +
P
3,4
(
x
) +
P
4,4
(
x
) = 1
P
1,4
(0) =
P
2,4
(0) =
P
3,4
(0) = 0.
In particular we have
P
4,4
(1) = (-5/4)*(cos(1) + sin(1)) + (1/2)*
e
-1
+ (
e
-1/2
)*(cos(sqrt(3)/2) + 5/sqrt(3)*sin(sqrt(3)/2)), or approximately 0.18343765086.
Congrats to this month’s solvers!

In [6]:
#exact solution. 4 player game doesn't simplify to the 3 player game on hit so gets tricky. 2 player game is tractable.
import sympy as sy
n = sy.symbols("n")

print("For the 2 player game the probability of second player winning is ")

form = sy.Sum((1-1/(2*n+1))*1/(sy.factorial(2*n)),(n,1,sy.oo))
print(form)
print(form.doit())


For the 2 player game the probability of second player winning is 
Sum((1 - 1/(2*n + 1))/factorial(2*n), (n, 1, oo))
-sinh(1) + cosh(1)


In [7]:
# simulate to check 
def game(players=4):
    live = np.ones(players)
    distance = np.sum(np.random.rand(2)**2)**0.5   
    player = 1
    while sum(live) > 1:
        if live[player] ==1:
            shot = np.sum(np.random.rand(2)**2)**0.5   
            if shot > distance:
                live[player] = 0
            else:
                distance = shot
        player = (player + 1 ) % players
        while live[player] ==0:
            player = (player + 1 ) % players
    return (live)    

In [8]:
start = time.time()
N= 10**5
for i in range(3):
    print(np.sum([game(4) for i in range(N)],axis=0)/N)
print("Took",time.time()-start)

[0.37311 0.24144 0.20328 0.18217]
[0.37079 0.24245 0.20359 0.18317]
[0.3712  0.24353 0.20513 0.18014]
Took 16.250579595565796
