In [1]:
import numpy as np
import time

In [2]:
#Forming the Puzzle Grid
class Matrix():
    def __init__(self,puzzle_string):
        self.grid = puzzle_string
        print('The problem - Start {}'.format(time.strftime('%X')))
        self.printGrid()
    
#Function to print the grid
    def printGrid(self):
        print(self.grid)
        
#Function to check if a digit can be placed in the given block
    def possible(self,row,col,digit):

        # Check row and columns count
        if digit ==0:
            if np.sum(grid[:,col]==0) > 2:
                return False
            if np.sum(grid[row,:]==0) > 2:
                return False
        
        # Check row and columns sum
        if np.sum(grid[:,col])+digit+np.sum(grid[:,col]==-1) > 20:
            return False
        
        if np.sum(grid[row,:])+digit+np.sum(grid[row,:]==-1)  > 20:
            return False
        
        #check 2x2
        if digit !=0:
            if self.twobytwo(row,col):
                return False
        
        # All tests pass return True
        return True
    
    def twobytwo(self,i,j):
        if (i > 0 and j > 0 and 
        grid[i-1,j-1] > 0 and 
        grid[i-1,j] > 0 and 
        grid[i,j-1] > 0):
            return True
    
        if (i > 0 and j < 6 and
        grid[i-1,j+1] > 0 and 
        grid[i-1,j] > 0 and 
        grid[i,j+1] > 0):
            return True
    
        if (i < 6 and j > 0 and
        grid[i+1,j-1] > 0 and 
        grid[i+1,j] > 0 and 
        grid[i,j-1] > 0):
            return True

    
        if (i < 6 and j < 6 and
        grid[i+1,j+1] > 0 and 
        grid[i+1,j] > 0 and 
        grid[i,j+1] > 0):
            return True
    
        return False
        
    
    def solve(self):
        counts = {i:i-np.sum(grid==i) for i in range(8)}
        for row in range(7):
            for col in range(7):
                if self.grid[row][col] == -1:
                    for digit in range(0,8):
                        if (digit ==0 or counts[digit]>0):
                            if self.possible(row,col,digit):
                                self.grid[row,col] = digit
                                counts[digit] -= 1
                                if self.solve():
                                    return True
                                self.grid[row,col] = -1  #Backtrack step
                                counts[digit] += 1
                    return False
        
        print('\nThe solution - End {}'.format(time.strftime('%X')))
        self.printGrid()



In [3]:
grid =np.array([[0,4,0,0,0,0,0],
                [0,0,6,3,0,0,6],
                [0,0,0,0,0,5,5],
                [0,0,0,4,0,0,0],
                [4,7,0,0,0,0,0],
                [2,0,0,7,4,0,0],
                [0,0,0,0,0,1,0]])


grid[grid==0]=-1

In [ ]:
x = Matrix(grid)
x.solve()


The problem - Start 21:31:32
[[-1  4 -1 -1 -1 -1 -1]
 [-1 -1  6  3 -1 -1  6]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1  4 -1 -1 -1]
 [ 4  7 -1 -1 -1 -1 -1]
 [ 2 -1 -1  7  4 -1 -1]
 [-1 -1 -1 -1 -1  1 -1]]
